name: CI
on: [workflow_dispatch, push]


jobs:
  Arduino-ESP32:
    runs-on: ubuntu-latest
    env:
      TARGET: esp32wrover
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        curl https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json --output /home/runner/.arduino15/package_esp32_index.json
        arduino-cli core install -v esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install -v ArduinoJson
        arduino-cli lib install -v --git-url https://github.com/axcap/Esp-GitHub-OTA.git

    - name: Compile Sketch
      run: arduino-cli compile -b esp32:esp32:${{ env.TARGET }}
      working-directory: examples/ESP32_example

  Arduino-ESP8266:
    runs-on: ubuntu-latest
    env:
      TARGET: nodemcuv2
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install dependencies
      run: |
        arduino-cli core update-index
        curl https://arduino.esp8266.com/stable/package_esp8266com_index.json --output /home/runner/.arduino15/package_esp8266com_index.json
        arduino-cli core install -v esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install -v ArduinoJson
        arduino-cli lib install -v --git-url https://github.com/axcap/Esp-GitHub-OTA.git

    - name: Compile Sketch
      run: arduino-cli compile -b esp8266:esp8266:${{ env.TARGET }}
      working-directory: examples/ESP8266_example

  PlatformIO-ESP32:
    runs-on: ubuntu-latest
    env:
      TARGET: nodemcu-32s # Must match the value after colon in platformio.ini (line 4: [env:nodemcu-32s])
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
      working-directory: examples/ESP32_example

  PlatformIO-ESP8266:
    runs-on: ubuntu-latest
    env:
      TARGET: nodemcuv2 # Must match the value after colon in platformio.ini (line 4: [env:nodemcuv2])
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
      working-directory: examples/ESP8266_example
